services:
#  web:
#    container_name: "web"
#    build:
#      context: ./EtudeWeb
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"
#    volumes:
#      - ./EtudeWeb:/app
#      - /app/node_modules
#    environment:
#      - NODE_ENV=development
#    restart: always

  auth:
    container_name: "auth"
    build:
      context: ./EtudeAuth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - authdb
    environment:
      - DB_HOST=authdb
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    restart: always
    networks:
      - solo
      - solo-etude
  
  authdb:
    container_name: "authdb"
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    networks:
      - solo
        
  db:
    container_name: "db"
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - etude

  redis:
    image: docker.io/redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --requirepass secret
    restart: always
    networks:
      - etude

  backend:
    container_name: "backend"
    build:
      context: ./EtudeBackend/EtudeBackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - etude
      - solo-etude
  
networks:
  etude:
  solo:
  solo-etude:
