networks:
  app-network:
  backend-db-network:

services:
  web:
    container_name: "web"
    image: etude-front:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  db:
    container_name: "db"
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - backend-db-network

  redis:
    image: docker.io/redis/redis-stack:latest
    environment:
      REDIS_ARGS: --requirepass secret
    restart: always
    networks:
      - backend-db-network

  backend:
    container_name: "backend"
    image: etude-backend:latest
    depends_on:
      - db
      - redis
    networks:
      - app-network
      - backend-db-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development