version: '3.8'

services:
  web:
    container_name: "web"
    image: etude-front:latest
    ports:
      - "3000:80"  # Nginx в фронтенд-образе слушает на порту 80
    environment:
      - NODE_ENV=development
    restart: always

  db:
    container_name: "db"
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --requirepass secret
    restart: always

  backend:
    container_name: "backend"
    image: etude-backend:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development