version: '3.8'

services:
  web:
    build:
      context: ./EtudeWeb
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./EtudeWeb:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped