name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest
    steps:
      # Шаг 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2. Билд фронтенд образа (сборка выполняется внутри Dockerfile)
      - name: Frontend Image Build
        uses: docker/build-push-action@v5
        with:
          context: ./EtudeWeb
          file: ./EtudeWeb/Dockerfile
          push: false
          tags: |
            etude-front:latest

      # Шаг 3. Билд бэкенд образа (сборка выполняется внутри Dockerfile)
      - name: Backend Image Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./EtudeBackend/EtudeBackend/Dockerfile
          push: false
          tags: |
            etude-backend:latest

      # Шаг 4. Образы в архивы
      - name: Images Packing
        run: |
          docker image save -o etude-front.tar etude-front:latest
          docker image save -o etude-backend.tar etude-backend:latest
          gzip etude-front.tar
          gzip etude-backend.tar
          chmod 777 etude-front.tar.gz
          chmod 777 etude-backend.tar.gz

      # Шаг 5. Перенос образов и docker-compose на сервер
      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./docker-compose.yml, etude-front.tar.gz, etude-backend.tar.gz"
          target: "/home/detouche-admin/Deployment/"

      # Шаг 6. Запуск контейнеров на сервере
      - name: Deploy Services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/detouche-admin/Deployment/
            docker compose down
            gunzip -f etude-front.tar.gz
            gunzip -f etude-backend.tar.gz
            docker load -i etude-front.tar
            docker load -i etude-backend.tar
            docker compose up -d
            rm -rf etude*.tar